# Generated by Django 5.1.4 on 2024-12-30 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='idea',
            name='application_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='idea',
            name='category',
            field=models.CharField(choices=[('job', 'Job/Internship Opportunity'), ('resource', 'Learning Resource/Tool')], default='resource', max_length=20),
        ),
        migrations.AddField(
            model_name='idea',
            name='company_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='idea',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='idea',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='idea',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
